name = "gparc"
version = "0.1.10"

description = "simple parser generators library on pure gleam"
licences = ["MIT"]
repository = { type = "github", user = "SpectralJager", repo = "gparc" }
# links = [{ title = "Website", href = "" }]
gleam = " >= 1.5.0"

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
